name: cv_project
description: CV for publish to Github.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_grid: ^2.1.0
  responsive_sizer: ^3.1.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/149071.jpeg
    - assets/images/facebook.png
    - assets/images/linkedin.png
    - assets/images/habr.png
    - assets/images/email.png
    - assets/images/github.png
    - assets/data/main-data.json
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Bold.ttf
        - asset: assets/fonts/Inconsolata-Regular.ttf
